collections:
  posts:
    output: true
    permalink: /articles/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

title: All In One Tools
description: Free online tools like JSON to XML, formatters, converters & more.
url: "https://allin1tools.netlify.app"
