collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
    _editable: true

_cloudcannon:
  collections_config:
    posts:
      icon: "book"
      name: "Blog Posts"
