collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
    _editable: true

_cloudcannon:
  collections_config:
    posts:
      icon: "book"
      name: "Blog Posts"
      
collections_config:
  posts:
    _icon: book
    _name: Blog Posts
    _singular_name: Blog Post
    _editor:
      preview: true
      time_format: HH:mm
    title:
      _label: Title
    date:
      _label: Date
    layout:
      _label: Layout
