backend:
  name: github
  repo: Anushenoy08/central-website
  branch: main

auth:
  client_id: Ov23liEnkW3GSXkNggR2
  redirect_uri: https://central-website.netlify.app/callback

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
